export {default as Homepage} from "./Homepage"
export {default as Navbar} from "./Navbar"
export {default as CryptoDetails} from "./CryptoDetails"
export {default as Crytocurrenceies} from "./Crytocurrenceies"
export {default as Exchanges} from "./Exchanges"
export {default as News} from "./News"
